SCR_EditorAttributeList {
 m_aAttributes {
  SCR_AIGlobalAIMAttribute "{684A9573B20D784B}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{684A9573B557AEE0}" {
    Name "Global AI Aim"
    Description "How Accurate AI When Shooting"
   }
   m_CategoryConfig "{A89ED6BFC0FE2AE4}Configs/Editor/AttributeCategories/AI_GlobalSystem.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{684A957360A9EF19}" {
    m_sSliderValueFormating "%1 Multiplier"
    m_fMin 0.1
    m_fMax 10
    m_fStep 0.1
    m_iDecimals 1
   }
  }
  SCR_AIIndividualAIMAttribute "{684A98469E8A533E}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{684A9846A6D68F5C}" {
    Name "AI Aim Accuracy"
   }
   m_CategoryConfig "{177D2D4588BC8389}Configs/Editor/AttributeCategories/Individual.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{684A984691F422DE}" {
    m_sSliderValueFormating "%1 Multiplier"
    m_fMin 0.1
    m_fMax 10
    m_fStep 0.1
    m_iDecimals 1
   }
  }
  SCR_AIGlobalPerceptionAttribute "{684E2D4C0DD0B01F}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{684E2D4C0FB67257}" {
    Name "Global AI Perception"
   }
   m_CategoryConfig "{A89ED6BFC0FE2AE4}Configs/Editor/AttributeCategories/AI_GlobalSystem.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{684E2D4C05B67299}" {
    m_fMin 0.5
    m_fMax 3
    m_fStep 0.1
    m_iDecimals 1
   }
  }
  SCR_AIIndividualPerceptionAttribute "{684E2D4C1F30EBB6}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{684E2D4C125EB6A6}" {
    Name "AI Perception"
   }
   m_CategoryConfig "{177D2D4588BC8389}Configs/Editor/AttributeCategories/Individual.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{684E2D4C2552EAFC}" {
    m_fMin 0.5
    m_fMax 3
    m_fStep 0.1
    m_iDecimals 1
   }
  }
  SCR_AIGlobalMagicAmmoAttribute "{68509B12C02C4993}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{68509B12C3208991}" {
    Name "Magic Magazine"
   }
   m_CategoryConfig "{A89ED6BFC0FE2AE4}Configs/Editor/AttributeCategories/AI_GlobalSystem.conf"
   m_Layout "{D0F3CE0C63A5AEBB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Checkbox.layout"
  }
  SCR_AIIndividualMagicAmmoAttribute "{68509B12F7BC8C3A}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{68509B12890C1397}" {
    Name "Magic Magazine"
   }
   m_CategoryConfig "{177D2D4588BC8389}Configs/Editor/AttributeCategories/Individual.conf"
   m_Layout "{D0F3CE0C63A5AEBB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Checkbox.layout"
  }
 }
}