SCR_EditorAttributeList {
 m_aAttributes {
  DCO_EnableAimImprovement "{64FA7A5812A52492}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{64FA7A58137B230C}" {
    Name "Enable Aim Improvement"
    Description "Enable AI Aim Improvement Over Time"
   }
   m_CategoryConfig "{0D1573D6D83136A2}Configs/Editor/AttributeCategories/DCO_Individual.conf"
   m_Layout "{D0F3CE0C63A5AEBB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Checkbox.layout"
  }
  DCO_MaxAimImprovementValue "{64FA7A5F2705423D}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{64FA7A5F22F8F2A7}" {
    Name "Aim Improvement Multiplier"
    Description "Multiplier Improvement AI Get"
   }
   m_CategoryConfig "{0D1573D6D83136A2}Configs/Editor/AttributeCategories/DCO_Individual.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{64FA7A5F1FF9C6DD}" {
    m_fMin 1
    m_fMax 10
    m_iDecimals 0
   }
  }
  DCO_MaxRangeAimImprovement "{64FA7A5F7DA84608}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{64FA7A5F7B1ED371}" {
    Name "Max Range Improvement"
    Description "Maximum Range AIM Improvement Can get Effect"
   }
   m_CategoryConfig "{0D1573D6D83136A2}Configs/Editor/AttributeCategories/DCO_Individual.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{64FA7A5F74B75C6E}" {
    m_fMin 1
    m_fMax 5000
    m_iDecimals 0
   }
  }
 }
}