SCR_EditorAttributeList {
 m_aAttributes {
  DCO_EnableAimImprovement "{64FA7A5812A52492}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{64FA7A58137B230C}" {
    Name "Enable Aim Improvement"
    Description "Enable AI Aim Improvement Over Time"
   }
   m_CategoryConfig "{0D1573D6D83136A2}Configs/Editor/AttributeCategories/DCO_Individual.conf"
   m_Layout "{D0F3CE0C63A5AEBB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Checkbox.layout"
  }
  DCO_MaxAimImprovementValue "{64FA7A5F2705423D}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{64FA7A5F22F8F2A7}" {
    Name "Aim Improvement Multiplier"
    Description "Multiplier Improvement AI Get"
   }
   m_CategoryConfig "{0D1573D6D83136A2}Configs/Editor/AttributeCategories/DCO_Individual.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{64FA7A5F1FF9C6DD}" {
    m_fMin 1
    m_fMax 20
    m_fStep 0.1
    m_iDecimals 1
   }
  }
  DCO_MaxRangeAimImprovement "{64FA7A5F7DA84608}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{64FA7A5F7B1ED371}" {
    Name "Max Range Improvement"
    Description "Maximum Range AIM Improvement Can get Effect"
   }
   m_CategoryConfig "{0D1573D6D83136A2}Configs/Editor/AttributeCategories/DCO_Individual.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{64FA7A5F74B75C6E}" {
    m_fMin 1
    m_fMax 5000
    m_iDecimals 0
   }
  }
  DCO_SkillLevel "{655C0997F0666B2A}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{655C0997DBFAA546}" {
    Name "DCO Skill"
    Description "Skill preset for AI"
   }
   m_CategoryConfig "{0D1573D6D83136A2}Configs/Editor/AttributeCategories/DCO_Individual.conf"
   m_Layout "{D1F686225704ADC2}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_ButtonBox_Selection.layout"
   m_aValues {
    SCR_EditorAttributeFloatStringValueHolder "{655C0992C3CDEBFA}" {
     m_sEntryName "Conscript"
    }
    SCR_EditorAttributeFloatStringValueHolder "{655C09923B38610F}" {
     m_sEntryName "Green"
     m_fEntryFloatValue 1
    }
    SCR_EditorAttributeFloatStringValueHolder "{655C09923B63E725}" {
     m_sEntryName "Regular"
     m_fEntryFloatValue 2
    }
    SCR_EditorAttributeFloatStringValueHolder "{655C099238D1A3C4}" {
     m_sEntryName "Veteran"
     m_fEntryFloatValue 3
    }
    SCR_EditorAttributeFloatStringValueHolder "{655C0992385BCE66}" {
     m_sEntryName "Crack"
     m_fEntryFloatValue 4
    }
    SCR_EditorAttributeFloatStringValueHolder "{655C09923983A1BE}" {
     m_sEntryName "Elite"
     m_fEntryFloatValue 5
    }
   }
   m_bHasRandomizeButton 1
   m_sRandomizeButtonIcon "{1A908AA553EDD94C}UI/Textures/Editor/Icon/2-Dice-Icon.svg.edds"
   m_fButtonHeight 90
  }
  DCO_GroupTacticsEditor "{658EF4A8D13A462D}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{658EF4A8D631972B}" {
    Name "Group Tactics"
   }
   m_CategoryConfig "{70DE63FC7A863B17}Configs/Editor/AttributeCategories/DCO_Group.conf"
   m_Layout "{D1F686225704ADC2}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_ButtonBox_Selection.layout"
   m_aValues {
    SCR_EditorAttributeFloatStringValueHolder "{658EF4AA71523FCA}" {
     m_Icon "{77B77BE4DBDC3A74}UI/Tactics/Aggresive.edds"
     m_sEntryName "Aggressive"
    }
    SCR_EditorAttributeFloatStringValueHolder "{658EF4AA712207D6}" {
     m_Icon "{BF02226E34AC3E79}UI/Tactics/Defensive.edds"
     m_sEntryName "Defensive"
     m_fEntryFloatValue 1
    }
    SCR_EditorAttributeFloatStringValueHolder "{658EF4AA70D72597}" {
     m_Icon "{FACB2104BA7420FC}UI/Tactics/Evasive.edds"
     m_sEntryName "Evasive"
     m_fEntryFloatValue 2
    }
    SCR_EditorAttributeFloatStringValueHolder "{658EF4ACD239C5FB}" {
     m_Icon "{C47E1E6CE93AEABF}UI/Tactics/Balanced.edds"
     m_sEntryName "Dynamic"
     m_fEntryFloatValue 3
    }
   }
   m_iButtonsOnRow 4
   m_fButtonHeight 90
  }
 }
}