SCR_EditorActionList {
 m_Actions {
  SCR_WaypointBaseCommandAction "{AEE6DF3BFE189B9A}" {
   m_Info SCR_UIInfo "{64C60022A2A31C19}" {
    Name "Garrison (DCO)"
    Description "Group occupies buildings in the waypoint radius: windows, roof, door guards, interior. Waypoint rotation = threat direction."
    Icon "{6FAED0D746483096}UI/Textures/Editor/Toolbar/Commanding/Toolbar_Commanding_Waypoint_Defend.edds"
   }
   m_ActionGroup COMMAND_WAYPOINT
   m_CommandPrefab "{BAF7BBB50B01F551}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Garrison.et"
  }
 }
}
