SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{684A8E47B1E30134}" {
  Name "AI Global System"
  Icon "{447DF80C8EE26E05}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Modes.edds"
 }
 m_iPriority 90
}