SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{684A8E47B1E30134}" {
  Name "AI Global System"
  Icon "{9FC60F54CB8C6C86}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Character.edds"
 }
 m_iPriority 90
}