SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{BC5533AE464F05F3}" {
  Name "DCO Commander Threat"
  Icon "{504479CFF2EDC299}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Factions.edds"
 }
 m_iPriority 94
}