SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{D0FF954A59E6BAD4}" {
  Name "DCO Objective"
  Icon "{504479CFF2EDC299}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Factions.edds"
 }
 m_iPriority 95
}