SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{CC2A1AF1C8281FC9}" {
  Name "DCO Commander Artillery"
  Icon "{504479CFF2EDC299}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Factions.edds"
 }
 m_iPriority 93
}