SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{60CE126E34047A51}" {
  Name "DCO Individual"
  Description "Individual editors"
  Icon "{EE6190435A9A84AA}UI/Textures/Editor/Attributes/Categories/IndividualIcon.edds"
 }
 m_iPriority 100
}