SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{65D8729F1DCDDC17}" {
  Name "DCO AI Global Setting"
  Description "Global Setting To ALL AI Applied to DCO"
  Icon "{EE6190435A9A84AA}UI/Textures/Editor/Attributes/Categories/IndividualIcon.edds"
 }
 m_iPriority 100
 m_bIsGlobalAttributeCategory 1
}