SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{0AE9BB335DD2898A}" {
  Name "DCO Global Combat"
  Icon "{447DF80C8EE26E05}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Modes.edds"
 }
 m_iPriority 87
}