SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{6A8F1C2D3E4B5A67}" {
  Name "DCO Global Reaction"
  Icon "{447DF80C8EE26E05}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Modes.edds"
 }
 m_iPriority 90
}