SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{99100219185C3A98}" {
  Name "DCO Global Players"
  Icon "{447DF80C8EE26E05}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Modes.edds"
 }
 m_iPriority 87
}