SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{6B2E4D8A1C7F3E90}" {
  Name "DCO Global Idle"
  Icon "{447DF80C8EE26E05}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Modes.edds"
 }
 m_iPriority 89
}