SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{28AFF96FCE3D0380}" {
  Name "DCO Global Contact Sharing"
  Icon "{447DF80C8EE26E05}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Modes.edds"
 }
 m_iPriority 86
}
