SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{29D1DA32505D9284}" {
  Name "DCO Global Medic"
  Icon "{447DF80C8EE26E05}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Modes.edds"
 }
 m_iPriority 88
}