SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{684A8E4794CD946B}" {
  Name "DCO Individual"
  Icon "{9FC60F54CB8C6C86}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Character.edds"
 }
 m_iPriority 90
}