SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{29136737664A8DB0}" {
  Name "DCO Squad Commander"
  Icon "{447DF80C8EE26E05}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Modes.edds"
 }
 m_iPriority 86
}