SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{68D64DDA8623E9ED}" {
  Name "DCO Squad"
  Icon "{18A629EECC5FAC79}UI/Textures/Editor/Attributes/Categories/Attribute_Category_Group.edds"
 }
 m_iPriority 90
}