SCR_PlaceableEntitiesRegistry {
 m_sAddon "DCO"
 m_Prefabs {
  "{9D54B8D0C2D6CD12}PrefabsEditable/DCO/Commander/E_AICommander.et"
  "{AC056675B421EB3A}PrefabsEditable/DCO/Commander/E_AICommander_Objective.et"
  "{6FBFC5635A33BD3D}PrefabsEditable/DCO/Commander/E_LogisticsHub.et"
  "{3CA16DA473A98543}PrefabsEditable/DCO/Commander/E_CommanderSpawner.et"
 }
}