SCR_MissionHeader {
 World "{98F117952A33B3C8}world/LostSoap.ent"
 m_sName "Operation : Lost Soap"
 m_sAuthor "DCO Team"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}