SCR_EditorActionList {
 m_Actions {
  DCO_SpawnerSpawnNowContextAction "{9B71ECD80CE8853B}" {
   m_Info SCR_UIInfo "{67F87ACDC4FB3CFE}" {
    Name "Spawn now"
    Icon "{3003692D3C8B0D0F}UI/Textures/Editor/ContextMenu/ContextAction_ObjectiveCancel.edds"
   }
   m_fCooldownTime 1
   m_bIsServer 1
  }
  DCO_HoldPositionContextAction "{69C2917828CB56B8}" {
   m_Info SCR_UIInfo "{69C291783BE4699B}" {
    Name "Hold Position"
    Icon "{3003692D3C8B0D0F}UI/Textures/Editor/ContextMenu/ContextAction_ObjectiveCancel.edds"
   }
   m_fCooldownTime 1
   m_bIsServer 1
  }
  DCO_UnholdPositionContextAction "{6A1F3C7E52B94D21}" {
   m_Info SCR_UIInfo "{6A1F3C7E52B94D22}" {
    Name "Unhold Position"
    Icon "{3003692D3C8B0D0F}UI/Textures/Editor/ContextMenu/ContextAction_ObjectiveCancel.edds"
   }
   m_fCooldownTime 1
   m_bIsServer 1
  }
 }
}
