SCR_EditorActionList {
 m_Actions {
  DCO_HoldPositionContextAction "{69C2917828CB56B8}" {
   m_Info SCR_UIInfo "{69C291783BE4699B}" {
    Name "Hold Position"
    Icon "{3003692D3C8B0D0F}UI/Textures/Editor/ContextMenu/ContextAction_ObjectiveCancel.edds"
   }
   m_fCooldownTime 1
   m_bIsServer 1
  }
 }
}